Repository prgrms-fe-devcourse/FEDC5_Bakers101_changyu, pull requests merged in 2024-01, with the labels that each got.

#18 로그인 기능 구현
  src/apis/.gitkeep
  src/apis/login.ts
  src/assets/.gitkeep
  src/assets/icons/bookmark.svg
  src/assets/icons/chat.svg
  src/assets/icons/comment.svg
  src/assets/icons/commentDelete.svg
  src/assets/icons/commentUpload.svg
  src/assets/icons/edit.svg
  src/assets/icons/fileUpload.svg
  src/assets/icons/following.svg
  src/assets/icons/notification.svg
  src/assets/icons/prev_brown.svg
  src/assets/icons/prev_white.svg
  src/assets/icons/profile.svg
  src/assets/icons/scrollTop.svg
  src/assets/icons/search.svg
  src/assets/icons/userlist.svg
  src/assets/icons/write.svg
  src/pages/.gitkeep
  src/pages/login/LoginForm.tsx
  src/pages/login/LoginStyles.ts
  src/utils/.gitkeep
Labels: feature, finish

#13 메인 홈 포스트 리스트 구현 및 포스트 생성 기능 , 채널 생성 및 관리 기능 구현
  .gitignore
  package.json
  src/App.tsx
  src/apis/channelApis.ts
  src/apis/postApis.ts
  src/apis/userApis.ts
  src/assets/icons/triangle.svg
  src/assets/temp/noImage.png
  src/pages/Home/components/Post/PostItem.tsx
  src/pages/Home/components/Post/PostList.tsx
  src/pages/Home/components/bottom-navbar/index.tsx
  src/pages/Home/components/channelSelectionsModal/index.tsx
  src/pages/Home/components/header/index.tsx
  src/pages/Home/index.tsx
  src/pages/PostCreation/Header.tsx
  src/pages/PostCreation/index.tsx
  src/utils/api_paths.ts
  src/utils/handleImageFormData.ts
  svg.d.ts
  tailwind.config.js
  yarn.lock
Labels: feature

#22 메인 홈, 로그인 ,회원 가입, 프로필 페이지 로직 연결
  src/App.tsx
  src/pages/Home/components/Post/PostItem.tsx
  src/pages/PostCreation/index.tsx
  src/pages/login/LoginForm.tsx
  src/pages/sign-up/SignupForm.tsx
Labels: combine

#21 검색 기능 페이지 구현
  src/apis/search/searchAll.ts
  src/apis/search/searchUser.ts
  src/assets/NoThumbnail.png
  src/hooks/useSearch.ts
  src/pages/search/components/CommentIcon.tsx
  src/pages/search/components/Filter.tsx
  src/pages/search/components/FilteredList.tsx
  src/pages/search/components/FilteredPost.tsx
  src/pages/search/components/FilteredUser.tsx
  src/pages/search/components/HeartIcon.tsx
  src/pages/search/components/NoProfileThumbnailIcon.tsx
  src/pages/search/components/NoResult.tsx
  src/pages/search/components/NoResultIcon.tsx
  src/pages/search/components/PrevIcon.tsx
  src/pages/search/components/SearchBar.tsx
  src/pages/search/components/SearchIcon.tsx
  src/pages/search/index.tsx
Labels: feature

#26 검색 결과 클릭 시, 사용자 프로필 페이지와 포스트 상세 페이지로 이동하는 기능 연결
  src/App.tsx
  src/apis/profile/updateName.ts
  src/apis/profile/updatePassword.ts
  src/apis/profile/uploadImage.ts
  src/pages/Home/components/header/index.tsx
  src/pages/Profile/components/CoverImage.tsx
  src/pages/Profile/components/ProfileImage.tsx
  src/pages/Profile/components/profile-edit-drawer/CoverImage.tsx
  src/pages/Profile/components/profile-edit-drawer/DrawerSide.tsx
  src/pages/Profile/components/profile-edit-drawer/ProfileImage.tsx
  src/pages/Profile/components/profile/UserProfileInfo.tsx
  src/pages/Profile/index.tsx
  src/pages/search/components/FilteredList.tsx
  src/pages/search/components/FilteredPost.tsx
  src/pages/search/components/FilteredUser.tsx
  src/pages/search/components/SearchBar.tsx
  src/pages/search/index.tsx
Labels: combine

#27 [HOTFIX] 수동 병합에서 발생한 스타일 문제 수정
  src/App.tsx
  src/pages/Home/components/Post/PostItem.tsx
  src/pages/Home/components/Post/PostList.tsx
  src/pages/Home/components/bottom-navbar/index.tsx
  src/pages/Home/components/channelSelectionsModal/index.tsx
  src/pages/Home/components/header/index.tsx
  src/pages/Home/index.tsx
  src/pages/PostCreation/Header.tsx
  src/pages/PostCreation/index.tsx
  src/pages/post-creation/index.tsx
  src/pages/post-detail/compoents/DeleteCheckModal.tsx
  src/pages/post-detail/compoents/PostBody.tsx
  src/pages/post-detail/compoents/PostHeader.tsx
  src/pages/post-detail/index.tsx
  src/pages/post-edit/components/Header.tsx
  src/pages/post-edit/index.tsx
Labels: refactor

#38 Hotfix / 삭제된 프로필 컴포넌트 & 병합 안된 부분 적용
  src/App.tsx
  src/components/login-notice-modal/index.tsx
  src/pages/Home/components/Post/PostItem.tsx
  src/pages/home/components/post/PostItem.tsx
  src/pages/post-creation/index.tsx
  src/pages/post-detail/compoents/PostBody.tsx
  src/pages/post-edit/index.tsx
  src/pages/profile/components/CoverImage.tsx
  src/pages/profile/components/EditIcon.tsx
  src/pages/profile/components/FollowIcon.tsx
  src/pages/profile/components/Header.tsx
  src/pages/profile/components/PrevIcon.tsx
  src/pages/profile/components/ProfileImage.tsx
  src/pages/profile/components/profile-edit-drawer/Drawer.tsx
  src/pages/profile/components/profile-edit-drawer/DrawerSide.tsx
  src/pages/profile/components/profile-edit-drawer/ProfileInput.tsx
  src/pages/profile/components/profile-edit-drawer/ProfileNameForm.tsx
  src/pages/profile/components/profile-edit-drawer/ProfilePasswordForm.tsx
  src/pages/profile/components/profile-edit-drawer/UploadImageButton.tsx
  src/pages/profile/components/profile/ButtonContainer.tsx
  src/pages/profile/components/profile/ChatIcon.tsx
  src/pages/profile/components/profile/FollowButton.tsx
  src/pages/profile/components/profile/PostList.tsx
  src/pages/profile/components/profile/UserProfileInfo.tsx
  src/pages/profile/index.tsx
Labels: fix

#32 알림 모달 구현, 댓글 추가 시 알림 생성
  src/apis/commnents.ts
  src/apis/notifications.ts
  src/components/comments/CommentForm.tsx
  src/components/notifications/NotificationItem.tsx
  src/components/notifications/NotificationList.tsx
  src/components/notifications/NotificationModal.tsx
  src/components/notifications/index.tsx
  src/hooks/.gitkeep
  src/hooks/useModal.ts
  src/pages/Home/components/bottom-navbar/index.tsx
  src/pages/Home/components/header/index.tsx
  src/stores/.gitkeep
Labels: feature

#33 포스트 수정 페이지에 이미지 변경, 채널변경 기능 추가
  src/App.tsx
  src/pages/home/components/Post/PostItem.tsx
  src/pages/home/components/Post/PostList.tsx
  src/pages/home/index.tsx
  src/pages/post-creation/components/Header.tsx
  src/pages/post-creation/index.tsx
  src/pages/post-edit/index.tsx
  src/utils/onGetImageFile.ts
Labels: feature

#31 팔로우, 팔로우 취소 기능 구현
  src/apis/follow/follow.ts
  src/apis/follow/unfollow.ts
  src/pages/home/components/bottom-navbar/index.tsx
  src/pages/home/components/channel-selections-modal/index.tsx
  src/pages/home/components/header/index.tsx
  src/pages/home/index.tsx
  src/pages/profile/components/EditIcon.tsx
  src/pages/profile/components/FollowIcon.tsx
  src/pages/profile/components/Header.tsx
  src/pages/profile/components/PrevIcon.tsx
  src/pages/profile/components/ProfileImage.tsx
  src/pages/profile/components/profile-edit-drawer/Drawer.tsx
  src/pages/profile/components/profile-edit-drawer/DrawerSide.tsx
  src/pages/profile/components/profile-edit-drawer/ProfileInput.tsx
  src/pages/profile/components/profile-edit-drawer/ProfileNameForm.tsx
  src/pages/profile/components/profile-edit-drawer/ProfilePasswordForm.tsx
  src/pages/profile/components/profile-edit-drawer/UploadImageButton.tsx
  src/pages/profile/components/profile/ButtonContainer.tsx
  src/pages/profile/components/profile/ChatIcon.tsx
  src/pages/profile/components/profile/FollowButton.tsx
  src/pages/profile/components/profile/PostList.tsx
  src/pages/profile/components/profile/UserProfileInfo.tsx
  src/pages/profile/index.tsx
Labels: feature

#44 [FIX] 사용자 목록 모달 구현 Re-PR
  src/apis/user/getAllUsers.ts
  src/apis/user/getOnlineUsers.ts
  src/pages/home/components/bottom-navbar/index.tsx
  src/pages/home/components/users-list-modal/Modal.tsx
  src/pages/home/components/users-list-modal/ProfileCard.tsx
  src/pages/home/components/users-list-modal/TabContent.tsx
  src/pages/home/components/users-list-modal/TabItem.tsx
  src/utils/api_paths.ts
Labels: feature, fix

#40 댓글 추가/삭제 시 포스트 상세 페이지에 댓글 개수 업데이트
  src/components/comments/CommentForm.tsx
  src/components/comments/CommentList.tsx
  src/components/comments/index.tsx
  src/pages/post-detail/compoents/PostBody.tsx
Labels: fix, refactor

#45 [FIX] 팔로우, 팔로위 취소 기능 구현 Re-PR
  src/pages/profile/components/profile-edit-drawer/ProfileInput.tsx
  src/pages/profile/components/profile-edit-drawer/ProfileNameForm.tsx
  src/pages/profile/components/profile-edit-drawer/ProfilePasswordForm.tsx
  src/pages/profile/components/profile/UserProfileInfo.tsx
  src/pages/profile/index.tsx
Labels: fix

#48 댓글 작성, 팔로우 시 알림 생성
  src/apis/commnents.ts
  src/apis/notifications.ts
  src/components/comments/CommentForm.tsx
  src/components/comments/index.tsx
  src/pages/post-detail/compoents/PostBody.tsx
  src/pages/post-detail/index.tsx
  src/pages/profile/index.tsx
Labels: feature

#47 로그아웃 기능 구현
  src/apis/logout.ts
  src/pages/profile/index.tsx
  src/stores/userProfileStore.ts
Labels: feature

#58 메인 홈 포스트 리스트 기능 개선 및 버그 수정
  src/apis/channelApis.ts
  src/apis/postApis.ts
  src/assets/icons/fireBreadIcon.svg
  src/pages/home/components/bottom-navbar/index.tsx
  src/pages/home/components/post/NonePost.tsx
  src/pages/home/components/post/PostItem.tsx
  src/pages/home/components/post/PostList.tsx
  src/pages/post-creation/index.tsx
  src/pages/post-detail/compoents/DeleteCheckModal.tsx
  src/pages/post-detail/index.tsx
  src/pages/post-edit/index.tsx
  src/utils/getPostCreateTime.ts
Labels: feature, fix, refactor

#50 프로필 페이지 & 프로필 편집 페이지 변경 점 적용
  src/hooks/useForm.ts
  src/pages/profile/components/profile-edit-drawer/DrawerSide.tsx
  src/pages/profile/components/profile-edit-drawer/ProfileInput.tsx
  src/pages/profile/components/profile-edit-drawer/ProfileNameForm.tsx
  src/pages/profile/components/profile-edit-drawer/ProfilePasswordForm.tsx
  src/pages/profile/components/profile/UserProfileInfo.tsx
  src/pages/profile/index.tsx
Labels: refactor

#51 사용자 목록 모달 변경 점 적용
  src/pages/home/components/users-list-modal/Modal.tsx
  src/pages/home/components/users-list-modal/ProfileCard.tsx
  src/pages/home/components/users-list-modal/TabContent.tsx
  src/pages/home/components/users-list-modal/TabItem.tsx
Labels: fix, refactor

#52 검색 페이지 변경 점 수정
  src/hooks/useSearch.ts
  src/pages/search/components/Filter.tsx
  src/pages/search/components/FilteredList.tsx
  src/pages/search/components/ResetIcon.tsx
  src/pages/search/components/SearchBar.tsx
Labels: refactor

#49 로그인 & 회원가입 이동안내 모달 구현 및 연결
  index.html
  src/App.tsx
  src/components/auth-route-modal/index.tsx
  src/components/comments/CommentForm.tsx
  src/components/notifications/NotificationModal.tsx
  src/pages/home/components/bottom-navbar/index.tsx
  src/pages/home/components/header/index.tsx
  src/pages/login/LoginForm.tsx
  src/pages/profile/components/CoverImage.tsx
  src/pages/profile/components/profile/UserProfileInfo.tsx
  src/pages/profile/index.tsx
  src/pages/sign-up/SignupForm.tsx
  src/stores/useAuthModalStore.ts
Labels: feature

#53 상세페이지 좋아요 기능 구현
  src/apis/likes.ts
  src/components/likes/LikedButton.tsx
  src/components/likes/Likes.tsx
  src/pages/post-detail/compoents/PostBody.tsx
Labels: feature

#55 회원가입 페이지 수정사항 구현
  src/pages/sign-up/SignupForm.tsx
Labels: refactor

#54 로그인 페이지 수정사항 구현
  src/pages/login/LoginForm.tsx
  src/pages/login/LoginStyles.ts
  src/pages/sign-up/SignupForm.tsx
  src/pages/sign-up/SignupStyles.ts
Labels: refactor

#62 [FIX] 사용자 목록 모달 UI 깨지는 현상 & 검색 키워드 초기화되지 않는 현상 수정
  src/hooks/useSearch.ts
  src/pages/home/components/bottom-navbar/index.tsx
  src/pages/home/components/users-list-modal/Modal.tsx
  src/pages/home/components/users-list-modal/ProfileCard.tsx
  src/pages/search/components/FilteredPost.tsx
  src/pages/search/components/SearchBar.tsx
  src/pages/search/index.tsx
Labels: fix

#67 Enter 키 눌렀을 때 댓글 추가
  src/components/comments/CommentForm.tsx
  src/pages/home/components/bottom-navbar/index.tsx
Labels: feature

#59 사용자가 로그인 되어있을때 로그인, 회원가입 페이지 접근시 홈으로 라우팅 시키는 기능 구현
  src/pages/login/LoginForm.tsx
  src/pages/sign-up/SignupForm.tsx
Labels: feature

#65 [FIX] 새로고침 하면 로그인 풀리는 오류, 팔로우 표시 잘안되는버그, 편집기 큰 이미지 버그 및 개선 사항 수정
  src/components/comments/CommentForm.tsx
  src/pages/home/components/bottom-navbar/index.tsx
  src/pages/home/components/header/index.tsx
  src/pages/home/components/post/PostItem.tsx
  src/pages/login/LoginForm.tsx
  src/pages/post-creation/index.tsx
  src/pages/post-detail/compoents/PostHeader.tsx
  src/pages/post-edit/index.tsx
  src/pages/profile/index.tsx
Labels: fix

#68 [hotfix] : 중복된 임포트문 제거
  src/pages/sign-up/SignupForm.tsx
Labels: fix

#71 Enter 키로 댓글 추가 오류, 좋아요 알림 오류 수정
  src/components/comments/CommentForm.tsx
  src/components/comments/index.tsx
  src/components/notifications/NotificationItem.tsx
  src/pages/profile/index.tsx
  src/types/type.d.ts
Labels: fix

#73 [TEST] 배포 테스트 PR
  .t
  src/apis/user/getAllUsers.ts
  src/components/comments/CommentForm.tsx
  src/components/comments/CommentList.tsx
  src/components/notifications/NotificationList.tsx
  src/hooks/useForm.ts
  src/pages/home/components/post/NonePost.tsx
  src/pages/home/components/post/PostList.tsx
  src/pages/home/components/users-list-modal/Modal.tsx
  src/pages/login/LoginForm.tsx
  src/pages/post-detail/index.tsx
  src/pages/post-edit/index.tsx
  src/pages/profile/components/profile-edit-drawer/ProfileNameForm.tsx
  src/pages/profile/components/profile-edit-drawer/ProfilePasswordForm.tsx
  src/pages/search/components/Filter.tsx
  src/pages/search/components/FilteredPost.tsx
  src/pages/search/components/FilteredUser.tsx
  src/pages/search/components/SearchBar.tsx
  src/pages/search/index.tsx
  vercel.json
Labels: test

#72 사용자 프로필 페이지에 작성한 포스트와 좋아요 한 포스트 렌더링
  src/pages/home/components/post/PostItem.tsx
  src/pages/home/components/post/PostList.tsx
  src/pages/login/LoginForm.tsx
  src/pages/profile/components/profile/LikedPostList.tsx
  src/pages/profile/components/profile/MyPostItem.tsx
  src/pages/profile/components/profile/MyPostLIst.tsx
  src/pages/profile/components/profile/PostList.tsx
  src/pages/profile/index.tsx
  src/types/type.d.ts
Labels: feature

#69 로그인 안됐을 때 좋아요 버튼 누르면 로그인 안내 모달 띄우는 기능 구현
  src/components/likes/Likes.tsx
  src/pages/login/LoginForm.tsx
Labels: feature

#74 사용하지 않는 라이브러리 및 모듈들을 제거 했습니다.
  package.json
  yarn.lock
Labels: refactor

#77 [Refactor] 토큰이 필요한 요청을 위한 axios 인스턴스(axiosInstanceWithToken) 추가 및 통일
  src/apis/api.ts
  src/apis/api_paths.ts
  src/apis/auth/login.ts
  src/apis/auth/logout.ts
  src/apis/auth/signup.ts
  src/apis/channel/createChannel.ts
  src/apis/channel/getChannelInform.ts
  src/apis/channel/getChannelList.ts
  src/apis/channelApis.ts
  src/apis/commnents.ts
  src/apis/follow/follow.ts
  src/apis/follow/unfollow.ts
  src/apis/likes.ts
  src/apis/notification/notifications.ts
  src/apis/post/commnents.ts
  src/apis/post/createPost.ts
  src/apis/post/deletePost.ts
  src/apis/post/getAllPostList.ts
  src/apis/post/getPostDetail.ts
  src/apis/post/getPostList.ts
  src/apis/post/likes.ts
  src/apis/post/updatePost.ts
  src/apis/postApis.ts
  src/apis/profile/profile.ts
  src/apis/profile/updateName.ts
  src/apis/profile/updatePassword.ts
  src/apis/profile/uploadImage.ts
  src/apis/search/searchAll.ts
  src/apis/search/searchUser.ts
  src/apis/user/getAllUsers.ts
  src/apis/user/getOnlineUsers.ts
  src/apis/userApis.ts
  src/components/comments/CommentForm.tsx
  src/components/comments/CommentList.tsx
  src/components/comments/index.tsx
  src/components/likes/Likes.tsx
  src/components/notifications/NotificationList.tsx
  src/components/notifications/NotificationModal.tsx
  src/pages/home/components/channel-selections-modal/index.tsx
  src/pages/home/components/post/PostItem.tsx
  src/pages/home/components/post/PostList.tsx
  src/pages/login/LoginForm.tsx
  src/pages/post-creation/index.tsx
  src/pages/post-detail/compoents/DeleteCheckModal.tsx
  src/pages/post-detail/index.tsx
  src/pages/post-edit/index.tsx
  src/pages/profile/index.tsx
  src/pages/sign-up/SignupForm.tsx
Labels: refactor

#75 프로필 페이지의 작성한 포스트 렌더링 방식 수정
  src/hooks/useForm.ts
  src/pages/home/components/users-list-modal/TabContent.tsx
  src/pages/profile/components/profile-edit-drawer/ProfileNameForm.tsx
  src/pages/profile/components/profile-edit-drawer/ProfilePasswordForm.tsx
  src/pages/profile/components/profile/MyPostItem.tsx
  src/pages/profile/components/profile/MyPostLIst.tsx
  src/pages/profile/components/profile/PostList.tsx
  src/pages/profile/index.tsx
  src/types/type.d.ts
Labels: refactor

#76 [Refactor & FIX] 라우트 수정 + 다크모드 색상 문제 해결
  src/App.tsx
  src/assets/not-found.png
  src/components/auth-route-modal/index.tsx
  src/pages/home/components/header/index.tsx
  src/pages/home/components/post/NonePost.tsx
  src/pages/home/components/users-list-modal/Modal.tsx
  src/pages/home/components/users-list-modal/TabContent.tsx
  src/pages/home/components/users-list-modal/TabItem.tsx
  src/pages/login/LoginForm.tsx
  src/pages/login/LoginStyles.ts
  src/pages/not-found/index.tsx
  src/pages/post-creation/components/header.tsx
  src/pages/post-creation/index.tsx
  src/pages/post-detail/compoents/DeleteCheckModal.tsx
  src/pages/post-detail/compoents/PostBody.tsx
  src/pages/post-detail/index.tsx
  src/pages/post-edit/components/Header.tsx
  src/pages/profile/components/CoverImage.tsx
  src/pages/profile/components/profile-edit-drawer/DrawerSide.tsx
  src/pages/profile/components/profile-edit-drawer/ProfileInput.tsx
  src/pages/profile/index.tsx
  src/pages/sign-up/SignupForm.tsx
  src/routes/Root.tsx
  src/routes/router.ts
Labels: refactor
